#!/usr/bin/env ruby
# frozen_string_literal: true

direction = ARGV[0]

res = `hyprctl dispatch movefocus #{direction}`

res.chomp exit if res == 'ok'

if %w[l u left up].include?(direction)
  system 'hyprctl dispatch workspace -1'
else
  system 'hyprctl dispatch workspace +1'
end
