#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

mark_tag = 'fullscreen'
size_prefix = 'was_'

win = JSON.parse(`hyprctl activewindow -j`)
width = win['size'][0]

mon = JSON.parse(`hyprctl monitors -j`)
mon_width = mon[0]['width']
tags = win['tags'] || []

if !tags.include?(mark_tag)
  rel = (width.to_f / mon_width).ceil(1)
  rel_s = rel.to_s.sub('.', '_')

  system("hyprctl dispatch tagwindow #{mark_tag}")
  system("hyprctl dispatch tagwindow #{size_prefix}#{rel_s}")
  system('hyprctl dispatch layoutmsg colresize 1')

else
  was = tags.find { |t| t.start_with?(size_prefix) }
  if was
    val = was.sub(size_prefix, '').sub('_', '.').to_f
    puts "val: #{val}"

    system("hyprctl dispatch tagwindow -- -#{was}")
    system("hyprctl dispatch layoutmsg colresize #{val}")
  end

  system("hyprctl dispatch tagwindow -- -#{mark_tag}")
end
