#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

clients = JSON.parse(`hyprctl clients -j`)
exists = clients.any? { |c| c['class'] == 'toggleterm' }

if exists
  system 'hyprctl dispatch togglespecialworkspace toggleterm'
else
  system '
    hyprctl dispatch exec \
    "[workspace special:toggleterm; float; size monitor_w*0.5 monitor_h*0.5] kitty --class toggleterm"
  '
end
