#!/usr/bin/env ruby
# frozen_string_literal: true

# set direction $argv[1]
# set changeto $argv[2]
#
# set pre (hyprctl -j activewindow | jq -r '.address')
# hyprctl dispatch movefocus $direction
# set post (hyprctl -j activewindow | jq -r '.address')
#
# if [ $pre = $post ]
#   hyprctl dispatch workspace $changeto
# end

direction = ARGV[0]

res = `hyprctl dispatch movefocus #{direction}`

res.chomp exit if res == 'ok'

if %w[l u left up].include?(direction)
  system 'hyprctl dispatch workspace -1'
else
  system 'hyprctl dispatch workspace +1'
end
