#!/usr/bin/env ruby
# frozen_string_literal: true

tries = 5

tries.times do
  wayland = ENV['WAYLAND_DISPLAY']
  wlr_ok = system('wlr-randr > /dev/null 2>&1')

  break if wayland && wlr_ok

  sleep 0.25
end

is_hyprland = ENV['XDG_CURRENT_DESKTOP'] == 'Hyprland'

hdmi_present = `wlr-randr`.lines.any? { |l| l.start_with?('HDMI-A-1') }

if is_hyprland
  # end script
  
end


if hdmi_present
    system('wlr-randr --output eDP-1 --off') unless is_hyprland
else
  system('wlr-randr --output eDP-1 --on') unless is_hyprland
end
